apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-syslog-ng
  labels:
    app.kubernetes.io/component: {{ $.Release.Name }}-syslog-ng
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ $.Release.Name }}-syslog-ng
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ $.Release.Name }}-syslog-ng
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/syslog-ng/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: syslog-ng
          image: "{{ .Values.syslog.image.repository }}:{{ .Values.syslog.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range $key, $values := .Values.syslog.services }}
          - name: {{ .name | default $key }}
            containerPort: {{ $values.containerPort }}
            protocol: {{ $values.protocol | default "TCP" }}
          {{- end }}
          volumeMounts:
          - name: {{ $.Release.Name }}-syslog-ng-config
            mountPath: /etc/syslog-ng
      volumes:
      - name: {{ $.Release.Name }}-syslog-ng-config
        configMap:
          name: {{ $.Release.Name }}-syslog-ng-config